name: Go

on:
  push:
    branches: [ "main" ]
    paths: ['yclient/**']
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
        cache-dependency-path: yclient/go.sum

    - name: Build
      run: make build

    - name: Test
      run: make test

    - uses: actions/upload-artifact@v4
      with:
        name: yclient
        path: .build/yclient
        if-no-files-found: error
        overwrite: true

