name: Update News Articles
on:
  workflow_dispatch:
  schedule:
    # at 5:00 AM
    - cron: "0 5 * * *"

permissions:
  actions: read
  packages: read
  contents: write
  pull-requests: write

env:
  updates_branch: release/daily-updates

jobs:
  update_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download yclient
        run: .github/workflows/scripts/download_artifact.sh Sprootsy yfeeder yclient .downloads
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: YClient
        run: |
          cd .downloads
          ./yclient -outDir ../website
        env:
          GENAI_API_KEY: "${{ secrets.GENAI_API_TOKEN }}"
      - name: Commit and Push
        run: |
          set -eo pipefail
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./website
          git commit -m "feat: update news items"
          git push origin "$updates_branch"
      - name: Merge with PR
        run: .github/workflows/scripts/do_pr.sh Sprootsy yfeeder "${GITHUB_REF_NAME}"
